def cnt(text, pattern):
	cnt = 0
	for i in range(len(text) - k + 1):
		part = text[i: i + k]
		if part == pattern:
			cnt += 1
	return cnt

text = 'TACTAGAAAATCAACGGGATGTGAAATACTAGAATACTAGAAATGTGAAAATGTGAAAAATCAACGGGGCCCAAATTTAATCAACGGGGCCCAAATTTGTACTCATGCGTACTCATGCGCCCAAATTTAATCAACGGGAATCAACGGGGTACTCATGCATGTGAAAATGTGAAATACTAGAAGCCCAAATTTTACTAGAAGTACTCATGCAATCAACGGGGCCCAAATTTATGTGAAATACTAGAATACTAGAATACTAGAATACTAGAAGTACTCATGCAATCAACGGGGCCCAAATTTAATCAACGGGGTACTCATGCATGTGAAAGCCCAAATTTGCCCAAATTTAATCAACGGGATGTGAAAGTACTCATGCAATCAACGGGATGTGAAAGCCCAAATTTGCCCAAATTTGCCCAAATTTAATCAACGGGTACTAGAAGCCCAAATTTATGTGAAATACTAGAAGCCCAAATTTGTACTCATGCGCCCAAATTTGCCCAAATTTGTACTCATGCGCCCAAATTTTACTAGAATACTAGAAGTACTCATGCTACTAGAAATGTGAAAGCCCAAATTTTACTAGAAATGTGAAATACTAGAAGCCCAAATTTAATCAACGGGGCCCAAATTTATGTGAAAAATCAACGGGGCCCAAATTTAATCAACGGGAATCAACGGGGTACTCATGCGTACTCATGCGTACTCATGCGTACTCATGCTACTAGAAAATCAACGGGTACTAGAAAATCAACGGGGCCCAAATTTGTACTCATGCGTACTCATGCATGTGAAAGCCCAAATTTGTACTCATGCATGTGAAATACTAGAATACTAGAATACTAGAAGTACTCATGCGTACTCATGCGCCCAAATTTATGTGAAAATGTGAAATACTAGAATACTAGAAAATCAACGGGTACTAGAA'
k = 13
ret = []
maxcount = 0
for i in range(len(text) - k + 1):
	pattern = text[i: i + k]
	count = cnt(text, pattern)
	if count > maxcount:
		ret = [pattern]
		maxcount = count
	elif count == maxcount:
		ret.append(pattern)
ret = list(set(ret))
print(' '.join(ret))